sudo: required
services:
  - docker

before_install:
  - docker build -t chaudharyp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chaudharyp/react-test npm run test

after_success:
  - docker build -t chaudharyp/multi-client ./client
  - docker build -t chaudharyp/multi-nginx ./nginx
  - docker build -t chaudharyp/multi-server ./server
  - docker build -t chaudharyp/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push chaudharyp/multi-client
  - docker push chaudharyp/multi-nginx
  - docker push chaudharyp/multi-server
  - docker push chaudharyp/multi-worker
    